In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Input=pd.read_csv("refresh9.csv",sep=",")
df= Input.dropna()
df

You_enjoy_spending_plenty_of_time_alone You_do_your_best_thinking_alone  \
0                                 disagree                          unsure   
1                                    agree                           agree   
2                                    agree                           agree   
3                                   unsure                          unsure   
4                                 disagree                          unsure   
5                                 disagree                          unsure   
6                                    agree                           agree   
7                                   unsure                          unsure   
8                                    agree                           agree   
9                                 disagree                        disagree   
10                                  unsure                        disagree   
11                                disagree                        disagree   
12                                disagree                        disagree   
13                                   agree                           agree   
14                                   agree                           agree   
15                                   agree                           agree   
16                                   agree                          unsure   
17                                   agree                           agree   
18                                disagree                        disagree   
19                                disagree                        disagree   
20                                   agree                          unsure   
21                                   agree                           agree   
22                                disagree                        disagree   
23                                   agree                           agree   
24                                disagree                        disagree   
25                                  unsure                          unsure   

   You_have_a_large_group_friends You_are_bored_when_you_are_alone  \
0                           agree                            agree   
1                          unsure                           unsure   
2                        disagree                         disagree   
3                           agree                            agree   
4                           agree                            agree   
5                           agree                            agree   
6                        disagree                         disagree   
7                           agree                            agree   
8                        disagree                         disagree   
9                           agree                            agree   
10                          agree                            agree   
11                          agree                            agree   
12                          agree                            agree   
13                         unsure                           unsure   
14                         unsure                           unsure   
15                       disagree                         disagree   
16                          agree                           unsure   
17                       disagree                         disagree   
18                          agree                            agree   
19                          agree                            agree   
20                         unsure                            agree   
21                       disagree                         disagree   
22                          agree                            agree   
23                       disagree                           unsure   
24                          agree                            agree   
25                          agree                            agree   

   Yo

In [3]:
df.shape

(26, 11)

In [4]:
df.dtypes

You_enjoy_spending_plenty_of_time_alone                       object
You_do_your_best_thinking_alone                               object
You_have_a_large_group_friends                                object
You_are_bored_when_you_are_alone                              object
You_have_no_desire_to_be_the_center_of_attention              object
You_avoid_small_talks_whenever_possible                       object
You_like_social_gatherings                                    object
You_are_a_natural_born_leader                                 object
You_are_better_at_writing_your_thoughts_than_speaking_them    object
You_speak_your_mind                                           object
personality                                                   object
dtype: object

In [5]:
df.head(10)

You_enjoy_spending_plenty_of_time_alone You_do_your_best_thinking_alone  \
0                                disagree                          unsure   
1                                   agree                           agree   
2                                   agree                           agree   
3                                  unsure                          unsure   
4                                disagree                          unsure   
5                                disagree                          unsure   
6                                   agree                           agree   
7                                  unsure                          unsure   
8                                   agree                           agree   
9                                disagree                        disagree   

  You_have_a_large_group_friends You_are_bored_when_you_are_alone  \
0                          agree                            agree   
1                         unsure                           unsure   
2                       disagree                         disagree   
3                          agree                            agree   
4                          agree                            agree   
5                          agree                            agree   
6                       disagree                         disagree   
7                          agree                            agree   
8                       disagree                         disagree   
9                          agree                            agree   

  You_have_no_desire_to_be_the_center_of_attention  \
0                                           unsure   
1                                           unsure   
2                                            agree   
3                                         disagree   
4                                         disagree   
5                                           unsure   
6                                            agree   
7                                           unsure   
8                                            agree   
9                                         disagree   

  You_avoid_small_talks_whenever_possible You_like_social_gatherings  \
0                                disagree                      agree   
1                                   agree                     unsure   
2                                   agree                   disagree   
3                                  unsure                      agree   
4                                disagree                      agree   
5                                disagree                      agree   
6                                disagree                   disagree   
7                                  unsure                      agree   
8                                disagree                   disagree   
9                                disagree                      agree   

  You_are_a_natural_born_leader  \
0                         agree   
1                      disagree   
2                      disagree   
3                         agree   
4                         agree   
5                         agree   
6                      disagree   
7                         agree   
8                      disagree   
9                         agree   

  You_are_better_at_writing_your_thoughts_than_speaking_them  \
0                                           disagree           
1                                           disagree           
2                                              agree           
3                                             unsure           
4                                           disagree           
5                                             unsure           
6                                              agree           
7                                              agree           
8                                           

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 26 entries, 0 to 25
Data columns (total 11 columns):
 #   Column                                                      Non-Null Count  Dtype 
---  ------                                                      --------------  ----- 
 0   You_enjoy_spending_plenty_of_time_alone                     26 non-null     object
 1   You_do_your_best_thinking_alone                             26 non-null     object
 2   You_have_a_large_group_friends                              26 non-null     object
 3   You_are_bored_when_you_are_alone                            26 non-null     object
 4   You_have_no_desire_to_be_the_center_of_attention            26 non-null     object
 5   You_avoid_small_talks_whenever_possible                     26 non-null     object
 6   You_like_social_gatherings                                  26 non-null     object
 7   You_are_a_natural_born_leader                               26 non-null     object
 8   You_are_bett

In [7]:
from sklearn import tree

In [8]:
X=df.drop(['personality'],axis=1)
print(df.isnull().values.any())

X.head(20)

False


You_enjoy_spending_plenty_of_time_alone You_do_your_best_thinking_alone  \
0                                 disagree                          unsure   
1                                    agree                           agree   
2                                    agree                           agree   
3                                   unsure                          unsure   
4                                 disagree                          unsure   
5                                 disagree                          unsure   
6                                    agree                           agree   
7                                   unsure                          unsure   
8                                    agree                           agree   
9                                 disagree                        disagree   
10                                  unsure                        disagree   
11                                disagree                        disagree   
12                                disagree                        disagree   
13                                   agree                           agree   
14                                   agree                           agree   
15                                   agree                           agree   
16                                   agree                          unsure   
17                                   agree                           agree   
18                                disagree                        disagree   
19                                disagree                        disagree   

   You_have_a_large_group_friends You_are_bored_when_you_are_alone  \
0                           agree                            agree   
1                          unsure                           unsure   
2                        disagree                         disagree   
3                           agree                            agree   
4                           agree                            agree   
5                           agree                            agree   
6                        disagree                         disagree   
7                           agree                            agree   
8                        disagree                         disagree   
9                           agree                            agree   
10                          agree                            agree   
11                          agree                            agree   
12                          agree                            agree   
13                         unsure                           unsure   
14                         unsure                           unsure   
15                       disagree                         disagree   
16                          agree                           unsure   
17                       disagree                         disagree   
18                          agree                            agree   
19                          agree                            agree   

   You_have_no_desire_to_be_the_center_of_attention  \
0                                            unsure   
1                                            unsure   
2                                             agree   
3                                          disagree   
4                                          disagree   
5                                            unsure   
6                                             agree   
7                                            unsure   
8                                             agree   
9                                          disagree   
10                                           unsure   
11                                         disagree   
12                                         disagree   
13                                            agree   
14                                            agree   
15           

In [9]:
y=df['personality'].values
y

array(['Extrovert', 'Introvert', 'Introvert', 'Extrovert', 'Extrovert',
       'Extrovert', 'Introvert', 'Extrovert', 'Introvert', 'Extrovert',
       'Extrovert', 'Extrovert', 'Extrovert', 'Introvert', 'Introvert',
       'Introvert', 'Extrovert', 'Introvert', 'Extrovert', 'Extrovert',
       'Introvert', 'Introvert', 'Extrovert', 'Introvert', 'Extrovert',
       'Extrovert'], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0])

In [11]:
X.replace(to_replace ='agree',value = 1,inplace=True)
X.replace(to_replace ='unsure',value = 2,inplace=True)
X.replace(to_replace ='disagree',value = 3,inplace=True)
X.head()

You_enjoy_spending_plenty_of_time_alone  You_do_your_best_thinking_alone  \
0                                        3                                2   
1                                        1                                1   
2                                        1                                1   
3                                        2                                2   
4                                        3                                2   

   You_have_a_large_group_friends  You_are_bored_when_you_are_alone  \
0                               1                                 1   
1                               2                                 2   
2                               3                                 3   
3                               1                                 1   
4                               1                                 1   

   You_have_no_desire_to_be_the_center_of_attention  \
0                                                 2   
1                                                 2   
2                                                 1   
3                                                 3   
4                                                 3   

   You_avoid_small_talks_whenever_possible  You_like_social_gatherings  \
0                                        3                           1   
1                                        1                           2   
2                                        1                           3   
3                                        2                           1   
4                                        3                           1   

   You_are_a_natural_born_leader  \
0                              1   
1                              3   
2                              3   
3                              1   
4                              1   

   You_are_better_at_writing_your_thoughts_than_speaking_them  \
0                                                  3            
1                                                  3            
2                                                  1            
3                                                  2            
4                                                  3            

   You_speak_your_mind  
0                    1  
1                    3  
2                    3  
3                    1  
4                    1

In [12]:
y

array([0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0])

In [13]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)


In [14]:
y_test

array([0, 1, 1, 0, 0, 0])

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold

In [16]:
regressor=DecisionTreeClassifier()
cv = KFold(n_splits=10, random_state=42, shuffle=False)

regressor.fit(X_train,y_train)

E:\don\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [17]:
#print(X_test.iloc[0])
#print(y_test.iloc[0])
y_pred = regressor.predict(X_test)
y_pred
#regressor.score(X_test,y_test)

array([0, 1, 1, 0, 0, 0])

In [18]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

1.0


In [19]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=51)
rf_classifier.fit(X_train,y_train)
y_pred_rf=rf_classifier.predict(X_test)
accuracy_score(y_test,y_pred_rf)

1.0

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

1.0


In [22]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=51)

In [23]:
rf_classifier.fit(X_train,y_train)
y_pred_rf=rf_classifier.predict(X_test)
accuracy_score(y_test,y_pred_rf)

1.0

In [24]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier=DecisionTreeClassifier(criterion='entropy',random_state=51)
dt_classifier.fit(X_train,y_train)
y_pred_dt=dt_classifier.predict(X_test)
accuracy_score(y_test,y_pred_dt)

1.0

In [25]:
import pickle
#with open('y_pred_pickle','wb') as f:
#   pickle.dump(y_pred,f)
    

In [26]:
filename = 'personality_final_model.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [27]:
loaded_model = pickle.load(open(filename, 'rb'))

In [28]:
y_pred = loaded_model.predict(X_test)
y_pred

array([0, 1, 1, 0, 0, 0])

In [29]:
print(accuracy_score(y_test,y_pred))

1.0
