In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Input=pd.read_csv("refresh7.csv",sep=",")
df= Input.dropna()
df

Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                               unsure             
1                                     strongly dislike             
2                                              dislike             
3                                              dislike             
4                                     strongly dislike             
..                                                 ...             
118                                            dislike             
119                                            dislike             
120                                   strongly dislike             
121                                             unsure             
122                                            dislike             

    Create_special_effects_for_movies/_edit_movies  \
0                                 strongly dislike   
1                                          dislike   
2                                          dislike   
3                                          dislike   
4                                 strongly dislike   
..                                             ...   
118                               strongly dislike   
119                               strongly dislike   
120                                        dislike   
121                                         unsure   
122                                         unsure   

    Give_career_guidance_to_people Manage_a_department_within_a_large_company  \
0                    strongly like                           strongly dislike   
1                 strongly dislike                                    dislike   
2                 strongly dislike                           strongly dislike   
3                    strongly like                                     unsure   
4                    strongly like                                     unsure   
..                             ...                                        ...   
118                        dislike                           strongly dislike   
119                         unsure                                       like   
120               strongly dislike                                    dislike   
121                         unsure                                       like   
122                           like                                    dislike   

    Manage_the_operations_of_a_hotel Study_the_movement_of_planets  \
0                             unsure                        unsure   
1                            dislike                 strongly like   
2                   strongly dislike                 strongly like   
3                   strongly dislike                       dislike   
4                   strongly dislike                          like   
..                               ...                           ...   
118                 strongly dislike                       dislike   
119                           unsure                        unsure   
120                           unsure              strongly dislike   
121                           unsure                          like   
122                             like                        unsure   

    Load_computer_software_into_a_large_computer_network  \
0                                              dislike     
1                                     strongly dislike     
2                                     strongly dislike     
3                                              dislike     
4                                     strongly dislike     
..                                                 ...     
118                                             unsure     
119                                               like     
120                                            dislike     
121                                             unsure     
122                                               like     

   

In [3]:
df.shape

(123, 52)

In [4]:
df.dtypes

Provide_physical_therapy_to_people_recovering_from_an_injury    object
Create_special_effects_for_movies/_edit_movies                  object
Give_career_guidance_to_people                                  object
Manage_a_department_within_a_large_company                      object
Manage_the_operations_of_a_hotel                                object
Study_the_movement_of_planets                                   object
Load_computer_software_into_a_large_computer_network            object
Assemble_electronic_parts                                       object
Compute_and_record_statistical_and_other_numerical_data         object
Act_in_a_play                                                   object
Study_space_travel                                              object
Conduct_chemical_experiments                                    object
Organize_and_schedule_office_meetings                           object
Teach_an_individual_or_a_group_of_students                      object
Handle

In [5]:
df.head(10)

Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                             unsure             
1                                   strongly dislike             
2                                            dislike             
3                                            dislike             
4                                   strongly dislike             
5                                             unsure             
6                                   strongly dislike             
7                                             unsure             
8                                   strongly dislike             
9                                             unsure             

  Create_special_effects_for_movies/_edit_movies  \
0                               strongly dislike   
1                                        dislike   
2                                        dislike   
3                                        dislike   
4                               strongly dislike   
5                               strongly dislike   
6                               strongly dislike   
7                                        dislike   
8                               strongly dislike   
9                                         unsure   

  Give_career_guidance_to_people Manage_a_department_within_a_large_company  \
0                  strongly like                           strongly dislike   
1               strongly dislike                                    dislike   
2               strongly dislike                           strongly dislike   
3                  strongly like                                     unsure   
4                  strongly like                                     unsure   
5                  strongly like                                     unsure   
6                        dislike                           strongly dislike   
7                        dislike                                     unsure   
8                  strongly like                                     unsure   
9                         unsure                           strongly dislike   

  Manage_the_operations_of_a_hotel Study_the_movement_of_planets  \
0                           unsure                        unsure   
1                          dislike                 strongly like   
2                 strongly dislike                 strongly like   
3                 strongly dislike                       dislike   
4                 strongly dislike                          like   
5                 strongly dislike                       dislike   
6                           unsure                 strongly like   
7                           unsure                 strongly like   
8                          dislike                          like   
9                 strongly dislike                 strongly like   

  Load_computer_software_into_a_large_computer_network  \
0                                            dislike     
1                                   strongly dislike     
2                                   strongly dislike     
3                                            dislike     
4                                   strongly dislike     
5                                            dislike     
6                                             unsure     
7                                            dislike     
8                                             unsure     
9                                   strongly dislike     

  Assemble_electronic_parts  \
0                   dislike   
1                   dislike   
2                   dislike   
3                   dislike   
4                    unsure   
5                    unsure   
6                    unsure   
7                    unsure   
8                      like   
9                    unsure   

  Compute_and_record_statistical_and_other_numerical_data     Act_in_a_play  \
0                      

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 123 entries, 0 to 122
Data columns (total 52 columns):
 #   Column                                                        Non-Null Count  Dtype 
---  ------                                                        --------------  ----- 
 0   Provide_physical_therapy_to_people_recovering_from_an_injury  123 non-null    object
 1   Create_special_effects_for_movies/_edit_movies                123 non-null    object
 2   Give_career_guidance_to_people                                123 non-null    object
 3   Manage_a_department_within_a_large_company                    123 non-null    object
 4   Manage_the_operations_of_a_hotel                              123 non-null    object
 5   Study_the_movement_of_planets                                 123 non-null    object
 6   Load_computer_software_into_a_large_computer_network          123 non-null    object
 7   Assemble_electronic_parts                                     123 non-null    ob

In [7]:
from sklearn import tree

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X=df.drop(['Career'],axis=1)
print(df.isnull().values.any())

X.head(20)

False


Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                              unsure             
1                                    strongly dislike             
2                                             dislike             
3                                             dislike             
4                                    strongly dislike             
5                                              unsure             
6                                    strongly dislike             
7                                              unsure             
8                                    strongly dislike             
9                                              unsure             
10                                            dislike             
11                                   strongly dislike             
12                                   strongly dislike             
13                                               like             
14                                             unsure             
15                                               like             
16                                             unsure             
17                                            dislike             
18                                             unsure             
19                                            dislike             

   Create_special_effects_for_movies/_edit_movies  \
0                                strongly dislike   
1                                         dislike   
2                                         dislike   
3                                         dislike   
4                                strongly dislike   
5                                strongly dislike   
6                                strongly dislike   
7                                         dislike   
8                                strongly dislike   
9                                          unsure   
10                               strongly dislike   
11                                        dislike   
12                               strongly dislike   
13                               strongly dislike   
14                                        dislike   
15                                         unsure   
16                                           like   
17                               strongly dislike   
18                                        dislike   
19                                        dislike   

   Give_career_guidance_to_people Manage_a_department_within_a_large_company  \
0                   strongly like                           strongly dislike   
1                strongly dislike                                    dislike   
2                strongly dislike                           strongly dislike   
3                   strongly like                                     unsure   
4                   strongly like                                     unsure   
5                   strongly like                                     unsure   
6                         dislike                           strongly dislike   
7                         dislike                                     unsure   
8                   strongly like                                     unsure   
9                          unsure                           strongly dislike   
10                        dislike                           strongly dislike   
11                  strongly like                                       like   
12                  strongly like                                    dislike   
13                           like                              strongly like   
14               strongly dislike                                     unsure   
15                        dislike                           strongly dislike   
16                         unsure                                       like   
17                        dislike        

In [10]:
y=df['Career'].values
y

array(['professor or teacher', 'Science', 'Science',
       'professor or teacher', 'professor or teacher',
       'professor or teacher', 'Science', 'Science',
       'professor or teacher', 'Science', 'Science',
       'professor or teacher', 'professor or teacher', 'Science',
       'Science', 'Science', 'Science', 'Arts', 'Arts',
       'Finance and Accounts', 'Arts', 'professor or teacher',
       'Finance and Accounts', 'Arts', 'Arts', 'Finance and Accounts',
       'Finance and Accounts', 'Arts', 'Finance and Accounts',
       'Finance and Accounts', 'Arts', 'Civil Services', 'Civil Services',
       'Civil Services', 'Civil Services', 'Civil Services',
       'Media and Entertainment', 'Media and Entertainment',
       'Civil Services', 'Civil Services', 'Media and Entertainment',
       'Civil Services', 'Civil Services', 'Media and Entertainment',
       'Media and Entertainment', 'Media and Entertainment', 'Startup',
       'Media and Entertainment', 'Startup', 'Management',

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([16, 13, 13, 16, 16, 16, 13, 13, 16, 13, 13, 16, 16, 13, 13, 13, 13,
        1,  1,  6,  1, 16,  6,  1,  1,  6,  6,  1,  6,  6,  1,  2,  2,  2,
        2,  2, 11, 11,  2,  2, 11,  2,  2, 11, 11, 11, 15, 11, 15,  9,  9,
        9, 15, 15,  9,  9, 15, 15,  9, 15,  9,  8,  8,  8,  8,  8,  8,  8,
        7,  7,  7,  0,  7,  0,  7,  7,  0,  5,  0,  5,  7,  0,  5,  0,  5,
        5, 10,  0,  5,  5, 14, 10, 14, 10, 10, 14, 10, 10, 14, 10, 14, 14,
       14,  4,  4,  4,  4, 12, 12, 12, 12,  4, 12,  4, 12, 12,  3,  3,  3,
        3,  3,  4,  3])

In [12]:
X.replace(to_replace ='strongly dislike',value = 1,inplace=True)
X.replace(to_replace ='dislike',value = 2,inplace=True)
X.replace(to_replace ='unsure',value = 3,inplace=True)
X.replace(to_replace ='like',value = 4,inplace=True)
X.replace(to_replace ='strongly like',value = 5,inplace=True)
X.head()

Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                                  3              
1                                                  1              
2                                                  2              
3                                                  2              
4                                                  1              

   Create_special_effects_for_movies/_edit_movies  \
0                                               1   
1                                               2   
2                                               2   
3                                               2   
4                                               1   

   Give_career_guidance_to_people  Manage_a_department_within_a_large_company  \
0                               5                                           1   
1                               1                                           2   
2                               1                                           1   
3                               5                                           3   
4                               5                                           3   

   Manage_the_operations_of_a_hotel  Study_the_movement_of_planets  \
0                                 3                              3   
1                                 2                              5   
2                                 1                              5   
3                                 1                              2   
4                                 1                              4   

   Load_computer_software_into_a_large_computer_network  \
0                                                  2      
1                                                  1      
2                                                  1      
3                                                  2      
4                                                  1      

   Assemble_electronic_parts  \
0                          2   
1                          2   
2                          2   
3                          2   
4                          3   

   Compute_and_record_statistical_and_other_numerical_data  Act_in_a_play  \
0                                                  1                    2   
1                                                  2                    1   
2                                                  1                    2   
3                                                  2                    4   
4                                                  1                    2   

   ...  Like_to_do_business_dealings  \
0  ...                             2   
1  ...                             3   
2  ...                             1   
3  ...                             1   
4  ...                             2   

   Want_to_know_about_trading_of_economic_value  \
0                                             2   
1                                             2   
2                                             1   
3                                             2   
4                                             3   

   Be_the_part_of_outdoor_games_during_any_festival  \
0                                                 1   
1                                                 3   
2                                                 1   
3                                                 2   
4                                                 4   

   Have_vital_national_interest  Want_to_live_adventurous_disciplined_lives  \
0                             1                                           1   
1                             3                                           3   
2                             1                                           1   
3                             3                                           3   
4                             3                                           2   

   Learn

In [13]:
y

array([16, 13, 13, 16, 16, 16, 13, 13, 16, 13, 13, 16, 16, 13, 13, 13, 13,
        1,  1,  6,  1, 16,  6,  1,  1,  6,  6,  1,  6,  6,  1,  2,  2,  2,
        2,  2, 11, 11,  2,  2, 11,  2,  2, 11, 11, 11, 15, 11, 15,  9,  9,
        9, 15, 15,  9,  9, 15, 15,  9, 15,  9,  8,  8,  8,  8,  8,  8,  8,
        7,  7,  7,  0,  7,  0,  7,  7,  0,  5,  0,  5,  7,  0,  5,  0,  5,
        5, 10,  0,  5,  5, 14, 10, 14, 10, 10, 14, 10, 10, 14, 10, 14, 14,
       14,  4,  4,  4,  4, 12, 12, 12, 12,  4, 12,  4, 12, 12,  3,  3,  3,
        3,  3,  4,  3])

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)


In [15]:
y_test

array([15,  4,  0,  4, 11,  2,  8, 15, 10,  0, 12,  2, 10,  3,  4,  3, 13,
        5, 12,  9,  8,  0,  7,  1,  5])

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold

In [17]:
regressor=DecisionTreeClassifier()
cv = KFold(n_splits=10, random_state=42, shuffle=False)

regressor.fit(X_train,y_train)

E:\don\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
#print(X_test.iloc[0])
#print(y_test.iloc[0])
y_pred = regressor.predict(X_test)
y_pred
#regressor.score(X_test,y_test)

array([15,  4,  0,  4,  8,  2,  8, 15, 10,  9, 12,  2, 10,  3,  4,  8, 13,
        5, 12,  9,  8,  0,  7,  1,  5])

In [19]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.88


In [20]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=51)
rf_classifier.fit(X_train,y_train)
y_pred_rf=rf_classifier.predict(X_test)
accuracy_score(y_test,y_pred_rf)

0.76

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.88


In [23]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=51)

In [24]:
rf_classifier.fit(X_train,y_train)
y_pred_rf=rf_classifier.predict(X_test)
accuracy_score(y_test,y_pred_rf)

0.76

In [26]:
import pickle
#with open('y_pred_pickle','wb') as f:
#   pickle.dump(y_pred,f)
    

In [31]:
filename = 'final_model.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [32]:
loaded_model = pickle.load(open(filename, 'rb'))

In [33]:
y_pred = loaded_model.predict(X_test)
y_pred

array([15,  4,  0,  4,  8,  2,  8, 15, 10,  9, 12,  2, 10,  3,  4,  8, 13,
        5, 12,  9,  8,  0,  7,  1,  5])

In [34]:
print(accuracy_score(y_test,y_pred))

0.88
