In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
Input=pd.read_csv("refresh6.csv",sep=",")
df= Input.dropna()
df

What_is_your_educational_level?  \
0                       post_matric   
1                 post_intermediate   
2                 post_intermediate   
3                   post_graduation   
4                   post_graduation   
..                              ...   
121                     post_matric   
122                     post_matric   
123               post_intermediate   
124               post_intermediate   
125                     post_matric   

    Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                     strongly dislike             
1                                              dislike             
2                                               unsure             
3                                                 like             
4                                                 like             
..                                                 ...             
121                                            dislike             
122                                            dislike             
123                                            dislike             
124                                             unsure             
125                                            dislike             

    Create_special_effects_for_movies/_edit_movies  \
0                                          dislike   
1                                             like   
2                                    strongly like   
3                                             like   
4                                             like   
..                                             ...   
121                                        dislike   
122                                        dislike   
123                                        dislike   
124                                         unsure   
125                                         unsure   

    Give_career_guidance_to_people Manage_a_department_within_a_large_company  \
0                             like                                       like   
1                             like                                     unsure   
2                    strongly like                                       like   
3                    strongly like                                       like   
4                    strongly like                                       like   
..                             ...                                        ...   
121                         unsure                                    dislike   
122                         unsure                                    dislike   
123                        dislike                                    dislike   
124                         unsure                                    dislike   
125                        dislike                                     unsure   

    Manage_the_operations_of_a_hotel Study_the_movement_of_planets  \
0                            dislike                          like   
1                      strongly like                          like   
2                            dislike                        unsure   
3                            dislike                 strongly like   
4                            dislike                          like   
..                               ...                           ...   
121                           unsure                       dislike   
122                           unsure              strongly dislike   
123                           unsure                       dislike   
124                           unsure                        unsure   
125                          dislike                        unsure   

    Load_computer_software_into_a_large_computer_network  \
0                                              dislike     
1                                                 like     
2                                               unsure     
3              

In [3]:
df.shape


(125, 52)

In [4]:
df.dtypes

What_is_your_educational_level?                                 object
Provide_physical_therapy_to_people_recovering_from_an_injury    object
Create_special_effects_for_movies/_edit_movies                  object
Give_career_guidance_to_people                                  object
Manage_a_department_within_a_large_company                      object
Manage_the_operations_of_a_hotel                                object
Study_the_movement_of_planets                                   object
Load_computer_software_into_a_large_computer_network            object
Assemble_electronic_parts                                       object
Draw_pictures                                                   object
Compute_and_record_statistical_and_other_numerical_data         object
Write_a_song                                                    object
Act_in_a_play                                                   object
Study_space_travel                                              object
Conduc

In [5]:
df.head(10)

What_is_your_educational_level?  \
0                     post_matric   
1               post_intermediate   
2               post_intermediate   
3                 post_graduation   
4                 post_graduation   
5                 post_graduation   
6                 post_graduation   
7               post_intermediate   
8               post_intermediate   
9               post_intermediate   

  Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                   strongly dislike             
1                                            dislike             
2                                             unsure             
3                                               like             
4                                               like             
5                                               like             
6                                      strongly like             
7                                               like             
8                                      strongly like             
9                                               like             

  Create_special_effects_for_movies/_edit_movies  \
0                                        dislike   
1                                           like   
2                                  strongly like   
3                                           like   
4                                           like   
5                                           like   
6                                           like   
7                                         unsure   
8                                  strongly like   
9                                           like   

  Give_career_guidance_to_people Manage_a_department_within_a_large_company  \
0                           like                                       like   
1                           like                                     unsure   
2                  strongly like                                       like   
3                  strongly like                                       like   
4                  strongly like                                       like   
5                           like                                       like   
6                  strongly like                                       like   
7                  strongly like                                       like   
8                  strongly like                                       like   
9                           like                              strongly like   

  Manage_the_operations_of_a_hotel Study_the_movement_of_planets  \
0                          dislike                          like   
1                    strongly like                          like   
2                          dislike                        unsure   
3                          dislike                 strongly like   
4                          dislike                          like   
5                          dislike                 strongly like   
6                             like                          like   
7                             like                 strongly like   
8                 strongly dislike                 strongly like   
9                             like                          like   

  Load_computer_software_into_a_large_computer_network  \
0                                            dislike     
1                                               like     
2                                             unsure     
3                                             unsure     
4                                               like     
5                                               like     
6                                             unsure     
7                                             unsure     
8                                               like     
9                                               like     

  Assemble_electronic_parts     Draw

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 125 entries, 0 to 125
Data columns (total 52 columns):
 #   Column                                                        Non-Null Count  Dtype 
---  ------                                                        --------------  ----- 
 0   What_is_your_educational_level?                               125 non-null    object
 1   Provide_physical_therapy_to_people_recovering_from_an_injury  125 non-null    object
 2   Create_special_effects_for_movies/_edit_movies                125 non-null    object
 3   Give_career_guidance_to_people                                125 non-null    object
 4   Manage_a_department_within_a_large_company                    125 non-null    object
 5   Manage_the_operations_of_a_hotel                              125 non-null    object
 6   Study_the_movement_of_planets                                 125 non-null    object
 7   Load_computer_software_into_a_large_computer_network          125 non-null    ob

In [7]:
from sklearn import tree

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X=df.drop(['Career'],axis=1)
print(df.isnull().values.any())

X.head(20)

False


What_is_your_educational_level?  \
0                      post_matric   
1                post_intermediate   
2                post_intermediate   
3                  post_graduation   
4                  post_graduation   
5                  post_graduation   
6                  post_graduation   
7                post_intermediate   
8                post_intermediate   
9                post_intermediate   
10                 post_graduation   
11               post_intermediate   
12                 post_graduation   
13                 post_graduation   
14               post_intermediate   
15                 post_graduation   
16                 post_graduation   
17                 post_graduation   
18                     post_matric   
19               post_intermediate   

   Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                    strongly dislike             
1                                             dislike             
2                                              unsure             
3                                                like             
4                                                like             
5                                                like             
6                                       strongly like             
7                                                like             
8                                       strongly like             
9                                                like             
10                                             unsure             
11                                               like             
12                                               like             
13                                               like             
14                                               like             
15                                            dislike             
16                                            dislike             
17                                      strongly like             
18                                   strongly dislike             
19                                   strongly dislike             

   Create_special_effects_for_movies/_edit_movies  \
0                                         dislike   
1                                            like   
2                                   strongly like   
3                                            like   
4                                            like   
5                                            like   
6                                            like   
7                                          unsure   
8                                   strongly like   
9                                            like   
10                                         unsure   
11                                        dislike   
12                                           like   
13                                           like   
14                               strongly dislike   
15                                           like   
16                                           like   
17                                           like   
18                               strongly dislike   
19                                  strongly like   

   Give_career_guidance_to_people Manage_a_department_within_a_large_company  \
0                            like                                       like   
1                            like                                     unsure   
2                   strongly like                                       like   
3                   strongly like                                       like   
4                   strongly like                                       like   
5                            like                                       like   
6                   strongly like                                       like   
7                   strongly like         

In [10]:
y=df['Career'].values
y

array(['Information Technology', 'Information Technology', 'Management',
       'Information Technology', 'Information Technology',
       'Information Technology', 'InformationTechnology',
       'InformationTechnology', 'InformationTechnology',
       'InformationTechnology', 'InformationTechnology',
       'InformationTechnology', 'InformationTechnology',
       'InformationTechnology', 'Science,_Medical',
       'Science,Engineering, InformationTechnology',
       'Science, Engineering, InformationTechnology', 'Management',
       'Media and Entertainment', 'Engineering', 'Medical',
       'Management, Marketing and Sales, Startup',
       'Science, Arts, Acting, Defence, Media and Entertainment, Startup, Civil Services',
       'Science, Engineering, Medical, Media and Entertainment, InformationTechnology, Startup, Finance and Accounts',
       'Science, Medical', 'Acting', 'Science, Sports, Engineering',
       'Acting, Media and Entertainment', 'Sports',
       'Sports, Engineer

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([11, 11, 15, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 30, 29, 23,
       15, 19,  9, 20, 17, 21, 24, 27,  0, 28,  1, 31, 32, 22, 26, 20,  2,
        1, 31,  6, 23, 16,  1,  8,  8, 18, 18, 25,  5,  5, 34, 31, 14,  3,
        3,  3, 15,  3,  3,  3,  3,  3,  3,  3, 10, 10, 10, 10, 13, 10, 10,
       10, 10, 10, 34, 34, 34, 34, 34, 34, 34, 34, 34, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 31,  4,  7,  7,  7,  4, 31,
        2,  4,  4,  7,  7,  4,  4, 31, 31,  4, 15, 15, 19,  4,  7, 31,  4,
       31, 31,  7,  4,  4,  7])

In [12]:
X['What_is_your_educational_level?'].replace(to_replace ='post_matric',value = 0,inplace=True)
X['What_is_your_educational_level?'].replace(to_replace ='post_intermediate',value =1,inplace=True)
X['What_is_your_educational_level?'].replace(to_replace ='post_graduation',value =2,inplace=True)
X['What_is_your_educational_level?'].replace(to_replace ='professional',value =3,inplace=True)
X.replace(to_replace ='strongly dislike',value = 0,inplace=True)
X.replace(to_replace ='dislike',value = 1,inplace=True)
X.replace(to_replace ='unsure',value = 2,inplace=True)
X.replace(to_replace ='like',value = 3,inplace=True)
X.replace(to_replace ='strongly like',value = 4,inplace=True)

X.head()

What_is_your_educational_level?  \
0                                0   
1                                1   
2                                1   
3                                2   
4                                2   

   Provide_physical_therapy_to_people_recovering_from_an_injury  \
0                                                  0              
1                                                  1              
2                                                  2              
3                                                  3              
4                                                  3              

   Create_special_effects_for_movies/_edit_movies  \
0                                               1   
1                                               3   
2                                               4   
3                                               3   
4                                               3   

   Give_career_guidance_to_people  Manage_a_department_within_a_large_company  \
0                               3                                           3   
1                               3                                           2   
2                               4                                           3   
3                               4                                           3   
4                               4                                           3   

   Manage_the_operations_of_a_hotel  Study_the_movement_of_planets  \
0                                 1                              3   
1                                 4                              3   
2                                 1                              2   
3                                 1                              4   
4                                 1                              3   

   Load_computer_software_into_a_large_computer_network  \
0                                                  1      
1                                                  3      
2                                                  2      
3                                                  2      
4                                                  3      

   Assemble_electronic_parts  Draw_pictures  ...  \
0                          2              1  ...   
1                          4              4  ...   
2                          3              4  ...   
3                          3              0  ...   
4                          3              3  ...   

   Audition_singers_and_musicians_for_a_musical_show  \
0                                                  0   
1                                                  3   
2                                                  4   
3                                                  3   
4                                                  3   

   Maintain_network_hardware_and_software  \
0                                       0   
1                                       3   
2                                       3   
3                                       2   
4                                       3   

   Set_up_and_operate_machines_to_make_products  \
0                                             1   
1                                             3   
2                                             2   
3                                             2   
4                                             3   

   Give_a_presentation_of_a_product_you_are_selling  \
0                                                 1   
1                                                 2   
2                                                 3   
3                                                 1   
4                                                 3   

   Spray_trees_to_prevent_the_spread_of_harmful_insects  \
0                                                  1      
1                                                  3      
2                                                  3 

In [13]:
y

array([11, 11, 15, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 30, 29, 23,
       15, 19,  9, 20, 17, 21, 24, 27,  0, 28,  1, 31, 32, 22, 26, 20,  2,
        1, 31,  6, 23, 16,  1,  8,  8, 18, 18, 25,  5,  5, 34, 31, 14,  3,
        3,  3, 15,  3,  3,  3,  3,  3,  3,  3, 10, 10, 10, 10, 13, 10, 10,
       10, 10, 10, 34, 34, 34, 34, 34, 34, 34, 34, 34, 33, 33, 33, 33, 33,
       33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 31,  4,  7,  7,  7,  4, 31,
        2,  4,  4,  7,  7,  4,  4, 31, 31,  4, 15, 15, 19,  4,  7, 31,  4,
       31, 31,  7,  4,  4,  7])

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)


In [15]:
y_test

array([34,  5, 31, 26, 13, 10,  4,  4,  4,  2, 10, 25,  7,  4, 31,  7, 31,
        4,  4, 15, 15,  4, 31,  3, 33])

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import KFold

In [17]:
regressor=DecisionTreeClassifier()
cv = KFold(n_splits=10, random_state=42, shuffle=False)

regressor.fit(X_train,y_train)

E:\don\lib\site-packages\sklearn\model_selection\_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [18]:
#print(X_test.iloc[0])
#print(y_test.iloc[0])
y_pred = regressor.predict(X_test)
y_pred
#regressor.score(X_test,y_test)

array([34,  5, 27, 21,  3, 10,  4,  4,  4, 30, 10,  9,  7,  4, 31,  7, 31,
        4,  4,  1,  3,  4, 31,  3, 12])

In [19]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.68


In [20]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=51)
rf_classifier.fit(X_train,y_train)
y_pred_rf=rf_classifier.predict(X_test)
accuracy_score(y_test,y_pred_rf)

0.68

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.68


In [23]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=20,criterion='entropy',random_state=51)

In [24]:
rf_classifier.fit(X_train,y_train)
y_pred_rf=rf_classifier.predict(X_test)
accuracy_score(y_test,y_pred_rf)

0.68

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt_classifier=DecisionTreeClassifier(criterion='entropy',random_state=51)
dt_classifier.fit(X_train,y_train)
y_pred_dt=dt_classifier.predict(X_test)
accuracy_score(y_test,y_pred_dt)

0.52

In [26]:
import pickle
#with open('y_pred_pickle','wb') as f:
#   pickle.dump(y_pred,f)
    

In [27]:
filename = 'finalized_model.sav'
pickle.dump(regressor, open(filename, 'wb'))

In [28]:
loaded_model = pickle.load(open(filename, 'rb'))

In [29]:
y_pred = loaded_model.predict(X_test)
y_pred

array([34,  5, 27, 21,  3, 10,  4,  4,  4, 30, 10,  9,  7,  4, 31,  7, 31,
        4,  4,  1,  3,  4, 31,  3, 12])

In [30]:
print(accuracy_score(y_test,y_pred))

0.68
